[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "verilog-eval"
version = "1.0.0"
description = "Verilog evaluation tool"
authors = [
  { name = "Your Name" }
]
dependencies = []